### ISSUE TITLE
Bet limit check on place bet

### ISSUE THREAD

**Issue by Raushantechfest** [IamAbhiKaushik/cobid_frontend#17]
When a person bets more coin than he has please put a poput notification saying he has bet more coins than he has. (attached video for reference)
[error cobid2.zip](https://github.com/IamAbhiKaushik/cobid_frontend/files/4537588/error.cobid2.zip)

**Comment by psg0796** [comment]
this needs to be handled from backend. Also don't send the bet count data for options from server for minimum bid type questions @IamAbhiKaushik

**Comment by psg0796** [comment]
Also @IamAbhiKaushik , is are you raising a error code such error 401 from backend. Can you make sure to either not raise that code or if raised then send a error message..

as of now for any invalid request an error code is raised and the error message is sent in response data, so I am unable to read the response data due to the error being raised.

**Comment by psg0796** [comment]
@IamAbhiKaushik also there is a bug, if I send a negative number it doesn't give me error. Pls make sure to raise error on decimals and negatives

**Comment by IamAbhiKaushik** [comment]
@psg0796 ,Let's convert the decimal values into int. 
and for negative values, I will return status: False and message=""

**Comment by IamAbhiKaushik** [comment]
done.
